var h;
if(!window.__idm_init__&&navigator.platform.startsWith("Win")&&"html"==document.documentElement.localName){window.__idm_init__=!0;"undefined"==typeof browser&&(browser=chrome);navigator.userAgent.includes("Edg/");navigator.userAgent.includes("Firefox/");navigator.userAgent.includes("OPR/");navigator.userAgent.includes("YaBrowser/");const N=Object.values,O=RegExp.prototype.test,P=Array.from,Q=Array.prototype.includes;Array.prototype.concat.bind([]);const Z=Math.random,aa=Function.call.bind(Array.prototype.slice),R=
Function.apply.bind(Array.prototype.push),G=Function.call.bind(Array.prototype.forEach),ba=Function.apply.bind(String.fromCharCode,null),H="dotAll"in RegExp.prototype?"s":"",ca=Function.call.bind(String.prototype.charCodeAt),da=String.fromCharCode;Function.bind.bind(function(a){return this[a]});Function.bind.bind(function(a){return a&&a[this]});TextDecoder.prototype.decode.bind(new TextDecoder("ascii"));TextEncoder.prototype.encode.bind(new TextEncoder("utf-8"));O.bind(/^(?:Host|Origin|Referer|Cookie|User-Agent|Connection|DNT|Accept-Encoding|Sec-.+)$/i);
Array.prototype.at||(Array.prototype.at=function(a){0>a&&(a+=this.length);return this[a]});AbortSignal.timeout||(AbortSignal.timeout=function(a){let b=new AbortController;globalThis.setTimeout(b.abort.bind(b),a);return b.signal});function ea(a,b){return fetch(a,b).catch(()=>null)}function fa(a,b){b&&(a[b]=!0);return a}function C(a){return a.replace(/[a-z]/gi,function(b){return da((b=ca(b))+(13<(b&31)?-13:13))})}const ha={16:!0,17:!0,18:!0,45:!0,46:!0},K=Q.bind(["video","audio","object","embed"]),
z=RegExp("(?!)"),ia=RegExp(" *\\$([<>{}|&*+=@!#%:?^~-])(\\d*) *"),ja=O.bind(/^rgba?\(\d+,\s*\d+,\s*\d+,\s*0\)/),I=window.self===window.top;var D=window.origin||document.origin||location.origin,J=location,L=location.hostname.toLowerCase()+location.pathname+location.search,S=location.hostname.toLowerCase().split(".").at(-2),T=`idmrs://${S}/`,ka=S?RegExp(`^(?:\\(\\d+\\)\\s+)?(.+?)\\s+[-|@]+\\s*${S}$`,"i"):z;function U(){browser.runtime.getFrameId?this.ea=browser.runtime.getFrameId(window):I&&(this.ea=
0);this.xa=[];this.P=[];this.S=[];this.j={};this.Wa();window.__idm_connect__=this.Wa.bind(this,!0);this.h(1,window,"resize",this.ec);this.h(1,window,"scroll",this.fc);this.h(1,window,"blur",this.Xb);this.h(1,window,"keydown",this.eb,!0);this.h(1,window,"keyup",this.eb,!0);this.h(1,window,"mousedown",this.Zb,!0);this.h(1,window,"mouseup",this.ac,!0);this.h(1,window,"mousemove",this.$b,!0);this.h(1,window,"click",this.Yb,!0);this.h(1,document,"beforeload",this.Vb,!0);this.h(1,document,"DOMContentLoaded",
this.cb);"interactive"!=document.readyState&&"complete"!=document.readyState||this.cb()}h=U.prototype;h.o=0;h.v=0;h.fa=-1;h.ga=-1;h.hb=1;h.T=0;h.l="";h.Da="";h.G="";h.Ka=z;h.Ra=RegExp(C('\\olgpst\\.frg\\(\\{(?=.*?"RKCREVZRAG_SYNTF":)(?=.*?"FGF":(\\q{5,})\\o|)(?=.*?"QNGNFLAP_VQ":"(.+?)"|)(?=.*?"YBTTRQ_VA":(\\j+)\\o|)(?=.*?"RBZ_IVFVGBE_QNGN":"(.+?)"|)(?=.*?"IVFVGBE_QNGN":"(.+?)"|)(?=.*?"CYNLRE_WF_HEY":"(.+?)"|)(?=.*?"FRFFVBA_VAQRK":"(\\q)"|)'),H);h.H=z;h.Ta=z;h.La=z;h.F={};h.Ma="(?!)";h.Na="(?!)";h.Oa=
C('\\oshapgvba\\((\\j+)\\)\\{ine\\f+(\\j+)=[^?;,]*?(?:\\.fcyvg\\.\\j+\\(\\1,|\\1\\.fcyvg\\()(?:.+?\\ovs\\f*\\(glcrbs\\f+([\\j$]+)===?(([\\j$]+)[^()]+|"haqrsvarq")\\)\\s*return\\b)?.+?\\{return\\s+(?:([\\w$]+)\\[\\d+\\]|[^();,]+?)\\+\\s*\\1\\}\\s*return\\b[^{};]+?(?:\\.join\\.\\w+\\(\\2,|\\2\\.join\\b)[^{};]+?\\}');h.Pa=C("(?<=\\oine\\f+)${3.3}=.+?(?=[;,}])");h.Qa=C("(?<=\\oine\\f+)${3.5}=(([\"']).*?\\2\\.fcyvg\\(([\"']).\\3\\)|\\[(?:(?:\".*?\"|'.*?')(?:,\\s*|(?=\\])))+\\])(?=[;,])");h.Sa=C('$> *[ebyr="znva"]:abg(uvqqra) ivqrb, :fpbcr >qvi#cynlre ivqrb, lgzhfvp-cynlre qvi#fbat-vzntr vzt');
h.Ja=C("$<< $> :fpbcr >ivqrb +qvi >pnainf");h.Ua=C("$= lg.pbasvt_.RBZ_IVFVGBE_QNGN $= lgpst.qngn_.RBZ_IVFVGBE_QNGN $= lg.pbasvt_.IVFVGBE_QNGN $= lgpst.qngn_.IVFVGBE_QNGN");h.la=z;h.ia=":root:empty";h.ka=0;h.ja=z;h.qa=z;h.ra='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div.xw7yly9 >div >div[style]:only-child $& div >article <';h.ta='$& div.xxzkxad $& :scope >div[class] $& section main[role="main"] $& div:first-child >div[role="button"][aria-hidden], article[role="presentation"] $& div:first-child >div[style]:first-child:empty < $& div[role="presentation"] >div >ul';
h.pa='$+ article:scope, div.x1xfsgkm:scope $* main[role="main"] article, main[role="main"] >div >div.x1xfsgkm';h.ua="$= poster $< <<<<<< $> div:scope >img:first-child, div[data-instancekey] div >img:first-child $= src";h.sa=RegExp("/(?:p|reel|reels|stories/[\\w.-]+)/([\\w-]{11}|\\d{19})(?:[/?#]|$)");h.Ea=z;h.Fa=RegExp("^(?:[^/]+|player\\.vimeo\\.com/video)/(\\d{2,})");h.Ia="$| video:scope $| video";h.Ga="$> :scope >div.player";h.Ha="$& div.vp-video $& div.vp-telecine";h.Wa=function(a){this.fb(-1);
this.g=a=browser.runtime.connect({name:(I?"top":"sub")+(a?":retry":"")+("file:"==location.protocol?":file":"")});this.h(-1,a,"onMessage",this.cc);this.h(-1,a,"onDisconnect",this.bc)};h.bc=function(){browser.runtime.lastError;this.fb();this.g=this.R=null;window.__idm_init__=!1;window.__idm_connect__=null};h.cc=function(a){switch(a.shift()){case 11:this.Cb.apply(this,a);break;case 17:this.Db.apply(this,a);break;case 12:this.Fb.apply(this,a);break;case 13:this.wb=a.shift();break;case 14:this.Ib.apply(this,
a);break;case 15:this.Jb.apply(this,a);break;case 16:this.Lb.apply(this,a);break;case 18:this.Hb.apply(this,a);break;case 19:this.Kb.apply(this,a)}};h.ic=function(a,b){var c=105<=this.N;let d=108<=this.N;switch(this.i=a){case 1:this.m=this.Eb=!0;if(a=b.shift())this.l=a;if(a=b.shift())this.Ka=RegExp(a,H);if(a=b.shift())this.H=RegExp(a);if(a=b.shift())this.Ta=RegExp(a);if(a=b.shift())this.F=a.split(/[|:]/).reduce(fa,{});if(a=b.shift())this.La=RegExp(a);if(a=b.shift())this.Ma=a;if(a=b.shift())this.Na=
a;(a=b.shift())&&c&&(this.Oa=a);(a=b.shift())&&c&&(this.Pa=a);(a=b.shift())&&c&&(this.Qa=a);(a=b.shift())&&d&&(this.Ra=RegExp(a,H));(a=b.shift())&&d&&(this.Sa=a);if(a=b.shift())this.Ja=a;if(a=b.shift())this.Ca=a;if(a=b.shift())this.Mb=a;if(a=b.shift())this.Ua=a;break;case 2:this.Ya();this.m=!0;if(a=b.shift())this.l=a;if(a=b.shift())this.G=a;if(a=b.shift())this.la=RegExp(a);if(a=b.shift())this.kb=a;if(a=b.shift())this.nb=a;b.shift();if(a=b.shift())this.na=a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=
b.shift())this.ob=a;if(a=b.shift())this.jb=a.startsWith("$")?a:`$* ${a}`;if(a=b.shift())this.oa=a.startsWith("$")?a:`$< ${a.slice(1)} <`;if(a=b.shift())this.gb=a;if(a=b.shift())this.ia=a;if(a=b.shift())this.pb=a.startsWith("$")?a:`$* ${a}`;if(c=b.shift())this.ka=c;if(a=b.shift())this.lb=a;if(a=b.shift())this.ja=RegExp(a);break;case 4:this.Ya();this.m=!0;if(a=b.shift())this.l=a;if(a=b.shift())this.Da=a;if(a=b.shift())this.G=a;if(a=b.shift())this.qa=RegExp(a);if(a=b.shift())this.sb=a;if(a=b.shift())this.ra=
a;if(a=b.shift())this.ta=a;if(a=b.shift())this.ub=a;if(a=b.shift())this.pa=a;if(a=b.shift())this.qb=a;if(a=b.shift())this.va=a;if(a=b.shift())this.ua=a;b.shift();if(a=b.shift())this.rb=a;if(a=b.shift())this.sa=RegExp(a);break;case 3:if(a=b.shift())this.Ea=RegExp(a);if(a=b.shift())this.Fa=RegExp(a);if(a=b.shift())this.Ia=a;if(a=b.shift())this.Ga=a;if(a=b.shift())this.Ha=a;break;case 5:this.m=!0;if(a=b.shift())this.l=a;if(a=b.shift())this.G=a;if(a=b.shift())this.vb=a;break;default:this.m=!0;if(a=b.shift())this.l=
a;if(a=b.shift())this.Ba=a}this.l.includes("^/")&&((b=this.Da)?b="https?://"+b.slice(+b.startsWith("^"),-b.endsWith("$")||void 0):b=D.replaceAll(".","\\."),this.l=this.l.replaceAll("^/",`^(?:${b})?/`))};h.$=function(a){if(this.i&&this.M(arguments))switch(this.i){case 1:this.Ub(a);break;case 2:this.Qb(a);break;case 4:this.Rb(a);break;case 3:this.Tb(a);break;case 5:this.Sb(a)}};h.W=function(a){let b=this.g;for(let c of document.getElementsByTagName("script"))!c.src&&a.test(c.text)&&b.postMessage([34,
null,-1,c.text]);b.postMessage([34,this.A()])};h.ca=function(a,b,c,d){if(this.ib&&c){let f=a instanceof Element?this.L(a):0,e=this.S,g=e.indexOf(null);0>g&&(g=e.length);e[g]=[a,b,d];window.postMessage([1229212980,g,f,c],"/")}else d(a,b)};h.dc=function(a,b){var c=this.S.splice(a,1,null).shift();if(c){a=c[0];let d=c[1];c=c[2];a instanceof Element&&!document.contains(a)&&(b=void 0);c(a,d,b)}};h.hc=function(a){let b=a.data;if(Array.isArray(b)&&a.origin==D)switch(b[0]){case 1229212977:window.postMessage([1229212978,
this.R,this.u,this.m,this.Eb,this.l,this.G],"/");this.ib=!0;break;case 1229212979:this.g.postMessage([36,b[1],b[2]]);break;case 1229212981:this.dc(b[1],b[2])}};h.X=function(){let a=window.devicePixelRatio,b=document.width,c=document.body.scrollWidth;b&&c&&(a=b==c?0:b/c);return a};h.Ya=function(){this.u||(this.u=btoa(Z().toString().substr(2,9)))};h.L=function(a){let b=a.s;b||(b=a.s=this.R<<13|this.hb++,this.j[b]=a,this.u&&a.setAttribute(this.u,b));return b};h.J=function(a){a.B&&(window.clearTimeout(a.B),
a.B=null);a.j&&(a.j.disconnect(),a.j=null);this.O&&this.O.unobserve(a);this.C&&this.C.unobserve(a);delete this.j[a.s];a.s=a.i=a.g=null};h.Va=function(a,b,c){let d=this.L(a);if(b||c){for(let f of N(this.j))if(b?b==f.i:c==f.g)return;a.g=c||T+a.localName+"/"+b;a.i=b}a.j||(b=a.j=new MutationObserver(this.aa.bind(this)),b.observe(a,{attributes:!0,attributeFilter:["style"]}),b.observe(a.parentElement,{childList:!0}),this.O&&this.O.observe(a));1==this.i&&t(a,this.Ca)&&(a.u=!0,a.C=10);return d};h.D=function(a,
b,c,d){if(b=this.Va(a,b,c))d&&this.C&&this.C.observe(a),d=this.K(a),this.g.postMessage([41,b,a.localName,a.src||a.data,a.g,a.i,d])};h.Bb=function(a,b,c,d,f,e){let g,m,k,n;let l,p,r=window.getComputedStyle.bind(window);try{let v=0;k=document.activeElement;k&&K(k.localName)||(k=document.elementFromPoint(this.fa,this.ga))&&!K(k.localName)&&(k=null);for(let q of document.querySelectorAll("video,audio,object,embed")){let B=q.localName,x;var w="object"==B||"embed"==B;if(w){let F=q.type.toLowerCase();if(F.startsWith("text/")||
F.startsWith("image/"))continue;if("embed"==B&&"application/x-shockwave-flash"!=F)continue}if(q.g&&!q.u&&(f||e))if(f?f==q.i:e==q.g)g=q;else continue;else if(x=q.src||q.data)x!=a&&x!=b||(g=q);else if(!w)for(let F of q.getElementsByTagName("source"))if((x=F.src)&&(x==a||x==b)&&(g=q))break;if(g)if("cover"==r(q).objectFit)m=q,g=null;else break;if(m||k||n)continue;if(x){if((x==c||x==d)&&(n=q))continue;if("video"==B&&x.startsWith("data:audio/"))continue}let A=q.clientWidth,y=q.clientHeight;if(!A||!y)continue;
let V=q.getBoundingClientRect();if(0>=V.right+window.scrollX||0>=V.bottom+window.scrollY)continue;let W=r(q);if(q.Y||"hidden"==W.visibility||"none"==W.display)"video"==B&&(p||=q);else{w=A*y;if(v<w&&1.35*A>y&&A<3*y){v=w;var u=q}l||=q}}}catch(v){}(a=g||m||k||n)?"video"!=a.localName&&"hidden"==r(a).visibility&&(a=null):a=u||l||p;a&&("embed"!=a.localName||a.clientWidth||a.clientHeight||(u=a.parentElement,"object"==u.localName&&(a=u)),this.Va(a,f,e));return a};h.Ab=function(a,b,c){let d=null,f,e=browser.runtime.getFrameId;
for(let g of document.getElementsByTagName("iframe")){let m=g.m;null==m&&e&&(m=g.m=e(g));if(m==a){d=g;break}else d||!(f=g.src)||f!=b&&f!=c||(d=g)}return d&&this.L(d)};h.K=function(a){let b=null;try{let c=window.getComputedStyle(a),d=a.getBoundingClientRect(),f=this.T,e=Math.round(d.width),g=Math.round(d.height),m;if("hidden"==c.visibility&&!a.contentWindow)return e>5*g?null:!1;if(0==c.opacity||a.Y)return!1;if(1==this.i&&0==a.offsetTop+a.offsetHeight){for(let u=a;u=u.parentElement;){let v=window.getComputedStyle(u);
if("block"!=v.display)break;if(0==v.opacity)return!1}d=a.parentElement.parentElement.getBoundingClientRect();f=0;"none"==c.display&&t(a,this.Ja)&&(e=Math.round(d.width),g=Math.round(d.height))}let k=Math.round(d.left)+a.clientLeft,n=Math.round(d.top)+a.clientTop;for(let u=0,v=0,q=a,B=c,x,A;f--&&"block"==B.display&&(x=q.parentElement)&&"div"==x.localName;q=x,B=A){A=window.getComputedStyle(x);u-=q.offsetLeft;v-=q.offsetTop;if("hidden"==A.overflowX){let y=e-x.offsetWidth-u;0<u&&(e-=u,k+=u);0<y&&(e-=
y);f=0}if("hidden"==A.overflowY){let y=g-x.offsetHeight-v;0<v&&(g-=v,n+=v);0<y&&(g-=y);f=0}}switch(a.localName){case "video":document.contains(a)&&(a.videoWidth||a.g||1>a.readyState&&2==a.networkState)&&(b=!1);if(15>e||10>g)return b;break;case "audio":if(1>e&&1>g)return b;m=!0}let l=document.documentElement,p=l.scrollWidth||l.clientWidth||document.body.scrollWidth,r=l.scrollHeight||l.clientHeight||document.body.scrollHeight;if(k>=p||n>=r||m&&!k&&!n)return b;0==k&&n==-r&&e==p&&g==r&&(n=0);let w=a.C||
0;b=[k,n+w,k+e,n+g-w,this.X()]}catch(c){}return b};h.tb=function(a){var b=a.Nb;if(b){b=document.elementsFromPoint((b.left+b.right)/2,(b.top+b.bottom)/2);for(var c,d;(c=b.shift())&&!c.isSameNode(a);){let f=window.getComputedStyle(c);if("visible"==f.visibility&&"0"!=f.opacity&&!ja(f.backgroundColor)){d=!0;break}}a.Y=d}};h.A=function(){let a=I?80:90;try{var b=window.top.document.title}catch(c){}b||(b=(b=document.head.querySelector('meta[property="og:title"]'))&&b.getAttribute("content"),a=70);b&&(b=
b.replace(/^\(\d+\)/,"").replace(/[ \t\r\n\u25B6]+/g," "),b=new String(b.trim()),b.src=a);return b};h.Gb=function(){if(!document.elementsFromPoint)return 0;var a=document.documentElement;let b=a.clientWidth||a.offsetWidth;a=(a.clientHeight||window.innerHeight)/4;var c=document.elementsFromPoint(0,0);let d=0,f=0,e=0;for(let m of c)if(m.offsetWidth>=b){var g=window.getComputedStyle(m);.95<=g.opacity&&(c=g.zIndex,"fixed"==g.position?(g=m.offsetHeight+m.offsetTop,d<g&&g<a&&(d=g,f=c)):e<c&&(e=c))}f<e&&
(d=0);return d};h.Cb=function(a,b,c,d,f,e,g,m,k){m&&X("text/javascript",m);this.N=a;this.R=b;if(d){this.ea=d;try{window.frameElement&&(window.frameElement.m=d)}catch(n){}}this.$a(e);f&&this.ic(f,aa(arguments,9));k&&(this.h(2,window,"message",this.hc),X("text/javascript",k));"loading"==document.readyState?this.ya=!0:this.$()};h.Db=function(a){L=location.hostname.toLowerCase()+location.pathname+location.search;this.za&&this.o&&(this.o=0,this.Aa=window.setTimeout(this.ba.bind(this,!1),3E3));this.$(!0);
a&&this.$a();for(let b of N(this.j))this.tb(b)};h.Kb=async function(a,b,c,d,f,e){let g=new Headers,m=AbortSignal.timeout(1E7);d={method:d,headers:g,body:e,signal:m,priority:"high",cache:"force-cache"};if(f&&f.length){for(let n of f)g.append(n.name,n.value);g.has("referer")&&(d.referrer=g.get("referer"))}g.has("accept")||g.append("accept","*/*");g.append("accept",`application/vnd.t1c.int-${a}`);c=await ea(c,d);let k;c&&200==c.status&&(0>b?(b=await c.arrayBuffer(),b=ba(b instanceof ArrayBuffer?new Uint8Array(b):
b)):b=await c.text(),k=b);this.g.postMessage([45,a,k])};h.$a=function(a){if(this.M(arguments)){var b=[21,J.href,document.referrer];a&&b.push(document.getElementsByTagName("video").length,document.getElementsByTagName("audio").length);this.g.postMessage(b)}};h.Ib=function(a){var b=a?this.M(arguments):1;if(0<b||0>b&&1!=this.i){b=this.A();let c=this.X(),d=this.Gb();this.g.postMessage([24,b,b&&b.src,c,d])}};h.Lb=function(a,b,c,d,f){c||=this.Ab(b,d,f);d=(d=c&&this.j[c])&&this.K(d);this.g.postMessage([22,
a,b,c,d])};h.Hb=function(a,b){let c,d,f=document.getElementsByTagName("a");for(let e of f)try{if(e.href==b){c=e.download||null;d=e.innerText.trim()||e.title||null;break}}catch(g){}this.g.postMessage([35,a,c,d])};h.Jb=function(a,b,c,d,f,e,g,m){if(this.M(arguments)){var k=[23,a,b,!1],n,l,p;if(b)b&&((n=this.j[b])||(k[3]=!0));else{if(n=this.Bb(c,d,f,e,m,g)){if(this.Ba&&(l=t(n,this.Ba)))var r=200;else if(l=n.getAttribute("operadetachedviewtitle"))r=130;k[2]=b=n.s;k[5]=n.localName;k[6]=n.src||n.data}else if(m||
g)k[3]=!0;!l&&(l=this.A())&&(r=l.src,(p=ka.exec(l))&&(l=p[1]));k[7]=l;k[8]=r}if(n)if(l=this.K(n),null!=l||document.contains(n)){if(k[4]=l,a&&1==this.i&&this.U)try{k[9]=window.sessionStorage.getItem(this.U)}catch(w){}}else this.J(n),k[3]=!0;this.g.postMessage(k)}};h.Fb=function(a,b,c,d){let f=d?RegExp(d,"i"):null;d=this.Za(document,f,b);let e=document.getElementsByTagName("iframe");for(let g of e)try{let m=g.contentDocument;m&&!g.src&&R(d,this.Za(m,f,b))}catch(m){}a=[27,a,this.ea,d.length];c||(a[4]=
d,a[5]=J.href,I&&(a[6]=J.href,a[7]=document.title));this.g.postMessage(a)};h.Za=function(a,b,c){let d=[],f={};var e="";let g="",m=!c,k;if(c&&(k=a.getSelection(),!k||k.isCollapsed&&!k.toString().trim()))return d;for(let l of a.getElementsByTagName("a"))if(m||k.containsNode(l,!0))try{let p=l.href;p&&!f[p]&&b.test(p)&&(f[p]=d.push([p,2,l.download||null,l.innerText.trim()||l.title]));c&&f[p]&&(g+=l.innerText,g+="\n")}catch(p){}for(let l of a.getElementsByTagName("area"))if(m||k.containsNode(l,!0))try{let p=
l.href;p&&!f[p]&&b.test(p)&&(f[p]=d.push([p,2,null,l.alt]))}catch(p){}for(let l of a.getElementsByTagName("img"))if(m||k.containsNode(l,!0))try{let p=l.src;p&&!f[p]&&b.test(p)&&(f[p]=d.push([p,3,null,"<<<=IDMTRANSMITIMGPREFIX=>>>"+l.alt]));m&&l.onclick&&(e+=l.onclick,e+="\n")}catch(p){}if(c){if(e=k.toString()){c=this.I(g);for(var n of this.I(e))n&&!f[n]&&b.test(n)&&!c.includes(n)&&(f[n]=d.push([n,1]))}for(let l of a.getElementsByTagName("textarea"))if(a=l.selectionStart,e=l.selectionEnd,(n=k.isCollapsed&&
a<e)||k.containsNode(l,!0))try{let p=n?l.value.substring(a,e):l.value;for(let r of this.I(p))r&&!f[r]&&b.test(r)&&(f[r]=d.push([r,1]))}catch(p){}}else{for(let l of a.getElementsByTagName("iframe"))try{let p=l.src;p&&!f[p]&&b.test(p)&&(f[p]=d.push([p,4]))}catch(p){}for(let l of a.getElementsByTagName("script"))e+=l.innerText,e+="\n";if(e)for(let l of this.I(e))l&&!f[l]&&b.test(l)&&(f[l]=d.push([l,5]))}return d};h.I=function(a){if(!this.wa){var b="\\b\\w+://(?:[%T]*(?::[%T]*)?@)?[%H.]+\\.[%H]+(?::\\d+)?(?:/(?:(?: +(?!\\w+:))?[%T/~;])*)?(?:\\?[%Q]*)?(?:#[%T]*)?".replace(/%\w/g,
function(d){return this[d]}.bind({"%H":"\\w\\- -﻿","%T":"\\w\\-.+*()$!,% -﻿","%Q":"^\\s\\[\\]{}()"}));this.wa=RegExp(b,"gi")}let c=[];for(;b=this.wa.exec(a);)c.push(b.shift());return c};h.M=function(a){let b=this.o;b||(a=P(a&&a.callee?a:arguments),a.unshift(arguments.callee.caller),this.P.push(a));return b};h.cb=function(a){let b;try{b=window.top.document.getElementsByTagName("title")[0]}catch(c){}this.o=a&&b?-1:1;b&&(a=this.za,a||(a=this.za=new MutationObserver(this.ba.bind(this))),a.observe(b,{childList:!0}));
try{this.O=new ResizeObserver(this.aa.bind(this))}catch(c){}try{this.C=new IntersectionObserver(this.aa.bind(this),{threshold:.2})}catch(c){}this.ya&&(this.ya=!1,this.$());for(let c,d=this.P;c=d.shift();)c.shift().apply(this,c)};h.aa=function(a){if(this.g)for(let b of a)if(a=b.target,a.s)if(document.contains(a)){let c=b.isIntersecting;null!=c&&(a.Y=!c,a.Nb=c?b.intersectionRect:null);a.B&&window.clearTimeout(a.B);a.B=window.setTimeout(this.Wb.bind(this,a),200)}else this.g.postMessage([23,null,a.s,
!0]),this.J(a)};h.Wb=function(a){if(!this.g)return this.J(a);a.B=null;let b=document.contains(a),c;if(b){if(c=this.K(a),1==this.i&&a.u)if(c){let d=t(a,this.Ca);d&&d.href&&d.href!=a.g&&this.D(a,null,d.href)}else a.g=a.i=null,b=!1}else this.J(a);this.g.postMessage([23,null,a.s,!b,c])};h.ba=function(a){if(a)window.clearTimeout(this.Aa),this.Aa=window.setTimeout(this.ba.bind(this,!1),1E3);else{0>this.o?this.o=1:++this.o;for(let b,c=this.P;b=c.shift();)b.shift().apply(this,b)}};h.Vb=function(a){var b=
a.target;let c=b.localName;K(c)&&a.url&&(b=this.L(b),this.g.postMessage([25,b,c,a.url]))};h.eb=function(a){!a.repeat&&ha[a.keyCode]&&this.g.postMessage([31,a.keyCode,"keydown"==a.type])};h.Zb=function(a){this.wb&&this.g.postMessage([28]);if(0==a.button){let b=a.view.getSelection();b&&b.isCollapsed&&!b.toString().trim()&&(this.v=1);this.g.postMessage([32,a.button,!0])}};h.ac=function(a){if(0==a.button){this.fa=a.clientX;this.ga=a.clientY;this.g.postMessage([32,a.button,!1]);let b=a.view.getSelection();
b&&this.v&&(this.v=b.isCollapsed&&!b.toString().trim()?0:2)&&this.g.postMessage([26,a.clientX,a.clientY,this.X()])}};h.$b=function(){2==this.v&&(this.v=0)};h.Yb=function(a){a=a.target;"a"==a.localName&&this.g.postMessage([39,a.hasAttribute("download"),a.href,a.download])};h.fc=function(){this.g.postMessage([29])};h.ec=function(a){a=a.target;this.g.postMessage([30,a.innerWidth,a.innerHeight])};h.Xb=function(){this.v=0;this.g.postMessage([33])};h.h=function(a,b,c,d,f){let e=P(arguments);e[3]=d.bind(this);
this.xa.push(e);0>a?(b=b[c],b.addListener.apply(b,e.slice(3))):b.addEventListener.apply(b,e.slice(2))};h.fb=function(a){let b=this.xa;for(let c=0;c<b.length;c++){let d=b[c][0];if(a&&a!=d)continue;let f=b.splice(c--,1).pop(),e=f.splice(0,2).pop();0>d?(e=e[f.shift()],e.removeListener.apply(e,f)):e.removeEventListener.apply(e,f)}};h.Ub=function(a){var b=this.Ta.exec(J.pathname+J.search);if(b){let w=t(document.body,this.Sa);w&&this.D(w,b[1])}if(!a){S="youtube";T="idmrs://youtube/";this.T=2;var c,d,f;
a=0;for(var e of document.getElementsByTagName("script")){if(e.src){if(b=this.H.exec(e.src))a|=1,this.F[b[1]]?f=b[1]:c=e.src}else if(b=this.Ra.exec(e.text)){a|=2;var g=b[1]&&parseInt(b[1],10);var m=b[2];var k="true"==b[3];var n=b[4]||b[5];var l=b[7]&&parseInt(b[7],10);if(b=this.H.exec(b[6]))this.F[b[1]]?f=b[1]:d=D+b[0]}else if(this.Ka.test(e.text)){a|=4;var p=e.outerHTML}if(7==a)break}b=101<=this.N;e=105<=this.N;(a=k?m:n)?this.U=Y(a):this.ca(window,k||!b?136:138,k?this.Mb:this.Ua,this.kc.bind(this));
if(f||g||m||n||l||null!=k)var r={[124]:f,[118]:g,[136]:k||b?m:n,[138]:n,[143]:l,[139]:k};(c||=d)&&e?(d=new XMLHttpRequest,d.responseType="text",d.timeout=1E4,d.onreadystatechange=this.lc.bind(this,c,r,p,d),d.open("GET",c,!0),d.send()):(r&&this.g.postMessage([37,1,2,r]),p&&this.g.postMessage([34,this.A(),null,p]))}};h.lc=function(a,b,c,d){if(4==d.readyState){d=d.response;var f=this.H.exec(a);a=this.La.exec(d);var e=f&&f[1],g=a&&parseInt(a[1]||a[2],10);if(g&&(!this.F[g]||!this.F[e])){a=[null,119,120,
135,141,142];f=[null,this.Ma,this.Na,this.Oa,this.Pa,this.Qa];e={[118]:g,[124]:e};let m=[];g=!0;let k=0;for(;g&&++k<f.length;){let n=f[k];1<k&&(n=n.replace(/\$\{(\d+)\.(\d+)\}/g,(l,p,r)=>m[p][r].replaceAll("$","\\$")));try{g=m[k]=RegExp(n,H).exec(d)}catch(l){g=null}}if(3<=k){for(d=1;d<a.length;d++)m[d]&&(e[a[d]]=m[d][0]);this.g.postMessage([37,1,1,e])}}b&&this.g.postMessage([37,1,2,b]);c&&this.g.postMessage([34,this.A(),null,c])}};h.kc=function(a,b,c){c&&(this.U=Y(c),this.g.postMessage([37,1,2,{[b]:c}]))};
function Y(a){let b=0,c=6038198,d=0,f;for(f=a.length>>1;b<f;b++)c=31*c+a.charCodeAt(b)|0;for(f=a.length;b<f;b++)d=31*d+a.charCodeAt(b)|0;return c.toString(16)+d.toString(16)}h.Qb=function d(b,c){b?(c&&b.shift().disconnect(),this.da.disconnect(),this.ma.disconnect(),this.ha.clear()):(this.W(this.la),this.da=new MutationObserver(this.yb.bind(this)),this.ma=new MutationObserver(this.xb.bind(this)),this.ha=new Set,this.T=3);if(c=this.mb=t(document.body,this.nb)){if(b=this.da,b.observe(c,{childList:!0}),
!this.Xa(c,!0)&&(c=t(c,this.ob))){var f=t(c,this.na);f?(b.observe(f,{childList:!0}),b.observe(c,{childList:!0})):b.observe(c.parentNode,{childList:!0})}}else!b&&(c=t(document.body,this.kb))&&(f=new MutationObserver(d.bind(this,b=[])),b.push(f),f.observe(c,{childList:!0}))};h.Xa=function(b,c){let d=this.da,f=this.na,e=this.jb,g=this.ma,m=this.ha,k=0;for(let n of t(b,e,[]))m.has(n)||t(n,e)||(m.add(n),g.observe(n,{childList:!0,subtree:!0}),c&&(b=t(n,f))&&(k++,d.observe(b,{childList:!0})),G(n.getElementsByTagName("video"),
this.V.bind(this)));return k};h.yb=function(b){let c=this.mb;for(let d of b){b=d.target.isSameNode(c);for(let f of d.addedNodes)1==f.nodeType&&this.Xa(f,b)}};h.xb=function(b){let c=this.S,d=this.oa;for(let f of b)for(let e of f.addedNodes)if(1==e.nodeType)if(b=e.getElementsByTagName("video"),b.length)G(b,this.V.bind(this));else for(let g of c)if(g){b=g[0];let m=t(b,d);m&&m.contains(e)&&this.V(b,!0)}};h.V=function(b,c){if(!b.g){var d=t(b,this.oa),f=d&&t(d,this.gb);if(!f){let m=this.ia,k=this.ka,n=
Q.bind(["div","span","a"]),l,p,r,w,u;for(let v=d;v&&k--&&n(v.localName);v=v.parentNode){p=v;let q;var e=v;var g=m+":scope:first-child:only-of-type";for(q=0;"<"==g[q];q++);q&&(g=g.slice(q));for(e=e.closest(g);e&&q--;e=e.parentElement);if(e)break;if((r=v.previousSibling)&&"div"==r.localName){l||=v.querySelector('div[role="slider"]');1==(u=v.querySelectorAll(m)).length?e=u[0]:(w=v.nextSibling)&&1==(u=w.querySelectorAll("ul:scope "+m)).length?e=u[0]:l&&1<(u=r.querySelectorAll(m)).length&&(e=u[u.length-
1]);break}}!e&&p&&1==(u=t(p,this.pb,[])).length&&(e=u[0]);!e&&d&&(e=d.querySelector(":scope >"+m));e&&(e=e.href);!e&&1==document.getElementsByTagName("video").length&&(f=this.ja.exec(J.href))&&(f=f[1])}f||e?this.D(b,f,e):c||this.ca(b,0,this.lb,this.zb.bind(this))}};h.zb=function(b,c,d){d&&this.D(b,d)};h.Rb=function(b){!b&&(this.W(this.qa),b=t(document.body,this.sb))&&(E(b,this.ra,this.Ob.bind(this)),E(b,this.ta,this.Z.bind(this)),E(b,this.ub,this.Z.bind(this)),E(document.body,this.qb,this.Z.bind(this)))};
h.ab=function(b,c,d){!c&&1==document.getElementsByTagName("video").length&&(c=this.sa.exec(J.href))&&(c=c[1]);this.D(b,c,d,!0)};h.Ob=function(b){for(let c of t(b,this.pa,[]))G(t(c,this.va,[]),this.bb.bind(this))};h.Z=function(b){G(t(b,this.va,[]),this.bb.bind(this))};h.bb=function(b){if(!b.g){var c=t(b,this.ua);c?this.ab(b,null,c):this.ca(b,0,this.rb,this.Pb.bind(this))}};h.Pb=function(b,c,d){d&&this.ab(b,d)};h.Tb=function(b){b||(this.W(this.Ea),(b=t(document.body,this.Ga))&&E(b,this.Ha,this.jc.bind(this)))};
h.jc=function(b){if(b=t(b,this.Ia)){let c=this.Fa.exec(L);c&&this.D(b,c[1])}};h.Sb=function(b){if(!b){var c=t(document.body,this.vb);c&&(b=this.A(),c=c.outerHTML,this.g.postMessage([34,b,null,c.slice(0,c.indexOf(">")+1)]))}};function X(b,c){b=document.createElement(b.startsWith("image/")?"img":"script");b.src=browser.runtime.getURL(c);b.onload=b.remove.bind(b);document.documentElement.appendChild(b)}function t(b,c,d){function f(p,r,w){for(;w&&r--;)w=w.parentElement;w&&(isNaN(p)||this.push(p),this.push(w));
return w}if(!c)return d;let e,g,m,k=!0,n=d||[],l=c.split(ia);for(1==l.length?l.unshift(">",NaN):l.shift();b&&(e=l.shift());){c=parseInt(l.shift(),10);g=l.shift().trim();for(m=1;"<"==g[g.length-m];m++);--m&&(g=g.slice(0,-m).trim());switch(e){case "<":b=M(g?b.closest(g):b,m);k=!0;break;case ">":b=M(b.querySelector(g),m);k=!0;break;case "{":b.closest(g)&&(b=null);break;case "}":b.querySelector(g)&&(b=null);break;case "|":if(g=g.endsWith(":scope")?b.closest(g):b.querySelector(g))return M(g,m);k=!1;break;
case "&":b=f.call(n,c,m,b.querySelector(g));k=!1;break;case "*":b.querySelectorAll(g).forEach(f.bind(n,c,m));k=!1;break;case "+":g=g?g.endsWith(":scope")?b.closest(g):b.querySelector(g):b;f.call(n,c,m,g);k=!1;break;case "=":if(g=b.getAttribute(g))return g;k=!1;break;case "@":if(g=b.textContent.trim())return g;k=!1}}return n.length?n:k&&b||d}function E(b,c,d,f,e,g){if(null==f){f=t(b,c,[]);g=new MutationObserver(E.bind(null,b,c,d,f));g.observe(b,{childList:!0});for(var m of f)g.observe(m,{childList:!0});
f.length&&d(f.at(-1))}else for(let k of e){for(let n of k.addedNodes)if(1==n.nodeType)if(e=t(b,c,[]).slice(f.length),(m=e.at(-1))&&n.contains(m)){R(f,e);for(let l of e)g.observe(l,{childList:!0});for(let l of m.children)d(l)}else k.target.isSameNode(f.at(-1)||b)&&d(n);for(let n of k.removedNodes)if(1==n.nodeType)for(e=0;e<f.length;e++)if(n.contains(f[e])){f.splice(e);break}}}function M(b,c){for(;b&&c--;b=b.parentElement);return b}NodeList.prototype[Symbol.iterator]||(NodeList.prototype[Symbol.iterator]=
Array.prototype[Symbol.iterator]);HTMLCollection.prototype[Symbol.iterator]||(HTMLCollection.prototype[Symbol.iterator]=Array.prototype[Symbol.iterator]);new U}!0;
